# -*- coding: utf-8 -*-
"""Calculating_Cosine_Similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/HodaMemar/A3/blob/main/Calculating_Cosine_Similarity.ipynb
"""

from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

df_RonS.hadm_ID.unique().tolist()
df_dis=pd.read_csv('...\Embedding.csv')
df_dis = df_dis.rename(columns={'Unnamed: 0': 'hadm_ID'})
df.iloc[:,0:200]
df_dis_RonS=df_dis[df_dis['hadm_ID'].isin(ls_RonS)]
list_patient=df_dis_RonS['hadm_ID'].unique().tolist()
len(list_patient)

title='Stage_S_ThirdTry_3'

df=pd.read_csv('D:\\Embedding\\Code\\A2021\\Embedding\\Emb_' + title + '.csv')
nVar=df.iloc[:,0:200]

indexx=df.admission_Id.tolist()
nVar

"""Convert dataframe to numpy format"""

var1=nVar.to_numpy()
var1

"""Calculation of cosine similarity between vectors"""

var2=cosine_similarity(var1, var1)
var2

"""Naming rows and columns with admission_ID"""

df1=pd.DataFrame(var2, index=[i for i in indexx])
df1.columns = indexx
#save as dataframe
df1.to_csv('...\\dis_'+title+'.csv')